[project]
name = "api-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SyedAsharAhmd", email = "syedasharahmed69@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.141.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "imagekitio>=5.10.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "typing-extensions>=4.16.0",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
api-test = "api_test:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
